---
pages:
- post/rep-tusovka.md
hide_body: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 2014-07-11 10:54:24 +0200
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
- name: title
  label: Title
  type: text
  hidden: false
  default: Post title
- name: slug
  label: Slug
  type: text
  hidden: false
  default: post-title
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - tag1
  - tag2
- name: image
  label: Image
  type: text
  hidden: false
  default: ''
- name: comments
  label: Comments
  type: boolean
  hidden: false
  default: true
- name: share
  label: Share
  type: boolean
  hidden: false
  default: true
- name: menu
  label: Menu
  type: text
  hidden: true
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
- type: select
  config:
    source:
      type: pages
- type: image_gallery
  hidden: false
